In [1]:
import numpy as np
import pandas as pd

In [5]:
max_num_features = 10
pad_size = 1
boundary_letter = -1
space_letter = 0

In [2]:
train_file_name = "../input/en_train.csv"

In [3]:
train_df = pd.read_csv(train_file_name)[:100]

In [7]:
# 每个目标词用组成这个词的所有字符的ascii码表示，并padding
x_data = []
for x, token_id in zip(train_df['before'].values, train_df["token_id"].values):
    if token_id == 0:
        x_row_before = np.zeros(max_num_features, dtype=int)
        x_data.append(x_row_before)
    x_row = np.ones(max_num_features, dtype=int) * space_letter

    for xi, i in zip(list(str(x)), np.arange(max_num_features)):
        x_row[i] = ord(xi)
    x_data.append(x_row)

In [8]:
x_data

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 66, 114, 105, 108, 108,  97, 110, 116,  97, 105]),
 array([105, 115,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([97,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([103, 101, 110, 117, 115,   0,   0,   0,   0,   0]),
 array([111, 102,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([112, 108,  97, 110, 116,   0,   0,   0,   0,   0]),
 array([105, 110,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([102,  97, 109, 105, 108, 121,   0,   0,   0,   0]),
 array([ 65,  99,  97, 110, 116, 104,  97,  99, 101,  97]),
 array([46,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([50, 48, 48, 54,  0,  0,  0,  0,  0,  0]),
 array([73, 85, 67, 78,  0,  0,  0,  0,  0,  0]),
 array([ 82, 101, 100,   0,   0,   0,   0,   0,   0,   0]),
 array([ 76, 105, 115, 116,   0,   0,   0,   0,   0,   0]),
 array([111, 102,   0,   0,   0,   0,   0,   0,   0,   0]),
 array([ 84, 104, 114, 101,  97, 116, 101, 110, 101, 100]),


In [19]:
def context_window_transform(data, pad_size):
    """每个词加上前面一个和后面一个词，中间用-1隔开"""
    pre = np.zeros(max_num_features, dtype=int)
    pre = [pre for x in np.arange(pad_size)]
    data = pre + data + pre
    print(data)
    new_data = []
    for i in np.arange(len(data) - pad_size * 2):
        if np.all(data[i + pad_size] == 0):
            continue
        row = []
        for x in data[i: i + pad_size * 2 + 1]:
            row += [boundary_letter]
            row += x.tolist()
        row += [boundary_letter]
        new_data.append(row)
    return new_data

In [20]:
x_data_context = context_window_transform(x_data, pad_size)

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([ 66, 114, 105, 108, 108,  97, 110, 116,  97, 105]), array([105, 115,   0,   0,   0,   0,   0,   0,   0,   0]), array([97,  0,  0,  0,  0,  0,  0,  0,  0,  0]), array([103, 101, 110, 117, 115,   0,   0,   0,   0,   0]), array([111, 102,   0,   0,   0,   0,   0,   0,   0,   0]), array([112, 108,  97, 110, 116,   0,   0,   0,   0,   0]), array([105, 110,   0,   0,   0,   0,   0,   0,   0,   0]), array([102,  97, 109, 105, 108, 121,   0,   0,   0,   0]), array([ 65,  99,  97, 110, 116, 104,  97,  99, 101,  97]), array([46,  0,  0,  0,  0,  0,  0,  0,  0,  0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([50, 48, 48, 54,  0,  0,  0,  0,  0,  0]), array([73, 85, 67, 78,  0,  0,  0,  0,  0,  0]), array([ 82, 101, 100,   0,   0,   0,   0,   0,   0,   0]), array([ 76, 105, 115, 116,   0,   0,   0,   0,   0,   0]), array([111, 102,   0,   0,   0,   0,   0,   0,   0,   0]), array([ 84, 104, 114, 101,  97, 116, 

In [21]:
np.shape(x_data_context)

(100, 34)